version: '3.9'

services:
    web:
        build: .
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - postgres

    postgres:
        image: pgrouting/pgrouting:13-3.0-3.1.0
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres