# Generated by Django 3.2.4 on 2021-07-01 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion

from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('codeRegion', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('codeRegion', models.CharField(blank=True, max_length=2, null=True)),
                ('codeDepartement', models.CharField(blank=True, max_length=3, null=True)),
                ('codesPostaux', models.CharField(blank=True, max_length=200, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appGeoFr.departement')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appGeoFr.region')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appGeoFr.region'),
        ),
    ]
