# Generated by Django 3.2.4 on 2021-07-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGeoFr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='codesPostaux',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
